service: patient-record

frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: us-east-2

functions:
  listPatients:
    handler: handler.listPatients
    events:
      - http:
          path:  patients
          method: get

  getPatient:
    handler: handler.getPatient
    events:
      - http:
          path:  patient/{patientId}
          method: get
